// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeightLossTracker.Data;

#nullable disable

namespace WeightLossTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415021713_AddMultiProfileSupport")]
    partial class AddMultiProfileSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("WeightLossTracker.Models.AiPromptLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("AiPromptLogs");
                });

            modelBuilder.Entity("WeightLossTracker.Models.ExerciseSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AiPromptLogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AiPromptLogId")
                        .IsUnique();

                    b.HasIndex("UserProfileId");

                    b.ToTable("ExerciseSuggestions");
                });

            modelBuilder.Entity("WeightLossTracker.Models.MealLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("MealLogs");
                });

            modelBuilder.Entity("WeightLossTracker.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FitnessLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("GoalWeight")
                        .HasColumnType("REAL");

                    b.Property<string>("Goals")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Injuries")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("StartingWeight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FitnessLevel = "Beginner",
                            GoalWeight = 190.0,
                            Goals = "Lose 25 lbs, build muscle",
                            Injuries = "Neck injury, lower back injury",
                            Name = "Default",
                            StartDate = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartingWeight = 215.0
                        });
                });

            modelBuilder.Entity("WeightLossTracker.Models.WeightEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "Date")
                        .IsUnique();

                    b.ToTable("WeightEntries");
                });

            modelBuilder.Entity("WeightLossTracker.Models.WorkoutScheduleDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("WorkoutScheduleDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 0,
                            Location = "Rest",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 1,
                            Location = "Home",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 2,
                            Location = "Home",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 3,
                            Location = "Home",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 4,
                            Location = "Home",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 5,
                            Location = "Home",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 6,
                            Location = "Rest",
                            UserProfileId = 1
                        });
                });

            modelBuilder.Entity("WeightLossTracker.Models.AiPromptLog", b =>
                {
                    b.HasOne("WeightLossTracker.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("WeightLossTracker.Models.ExerciseSuggestion", b =>
                {
                    b.HasOne("WeightLossTracker.Models.AiPromptLog", "AiPromptLog")
                        .WithOne()
                        .HasForeignKey("WeightLossTracker.Models.ExerciseSuggestion", "AiPromptLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WeightLossTracker.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiPromptLog");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("WeightLossTracker.Models.MealLog", b =>
                {
                    b.HasOne("WeightLossTracker.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("WeightLossTracker.Models.WeightEntry", b =>
                {
                    b.HasOne("WeightLossTracker.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("WeightLossTracker.Models.WorkoutScheduleDay", b =>
                {
                    b.HasOne("WeightLossTracker.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
